
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: wormhole
  password: wormhole
  host: localhost

development:
  <<: *default
  database: wormhole_development

test:
  <<: *default
  database: wormhole_test

production:
  <<: *default
  host: localhost
  database: wormhole_production
  username: wormhole
  password: <%= ENV['WORMHOLE_DATABASE_PASSWORD'] %>
