
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: wormhole
  password: rooroo

development:
  <<: *default
  database: wormhole_development

test:
  <<: *default
  database: wormhole_test

production:
  <<: *default
  database: wormhole_production
  username: wormhole
  password: <%= ENV['WORMHOLE_DATABASE_PASSWORD'] %>
